version: "3"

services:
  samba:
    container_name: samba
    volumes:
      - ${SAMBA_PATH}:/share
    ports:
      - 139:139
      - 445:445
    image: dperson/samba
    command: -p -s "public;/share;yes;no;yes"
    restart: always

networks:
  default:
    name: 1panel-network
    external: true
